services:
  - type: web
    name: tock-to-corksy-sync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: SHEET_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
